
import ProductInterface from '../models/products';

const productDB: ProductInterface[] = [
    {
        id: '1',
        name: 'iPhone 14 Pro Max',
        category: 'smartphones',
        brand: 'apple',
        release: '2022',
        color: 'Deep Purple',
        model: '(MQC53)',
        price: '1,599', 
        storage: '1Tb',
        imgs: ['./assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-deep-purple-1.jpg',
        './assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-deep-purple-2.jpg',
        './assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-deep-purple-3.jpg',
        './assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-deep-purple-4.jpg',
        './assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-deep-purple-5.jpg',
        './assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-deep-purple-6.jpg'],
        rating: 5,
        stock: 101,
        displaySize: `6.7''`,
        display: 'Super Retina XDR OLED',
        resolution: '2778 x 1284',
        ppi: '458ppi',
        refreshRate: '120Hz',
        communication: 'GPS; Wi-Fi; Bluetooth; Lightning',
        features: 'wireless charging; face ID; quick charge; LiDAR, emergency SOS via satellite',
        batteryType: 'Li-Ion',
        sdCardSupport: 'no',
        internet: '3G; 5G; 4G (LTE)',
        numOfSIMs: '1 + eSIM',
        typeOfSIM: 'Nano-SIM; eSIM',
        chipset: 'Apple A16 Bionic',
        cameras: '48MP + 12MP + 12MP + 12MP',
        maxVideoRecording: '2160p@60fps',
        bluetooth: '5.3',
        nfc: 'yes',
        os: 'iOS',
        osVersion: '16',
        protection: 'IP68',
        material: 'glass',
        size: '160.7 x 77.6 x 7.85mm',
        weight: '255g'
    },
    {
        id: '2',
        name: 'iPhone 14 Pro Max',
        category: 'smartphones',
        brand: 'apple',
        release: '2022',
        color: 'Gold',
        model: '(MQ9W3)',
        price: '1,199', 
        storage: '256Gb',
        imgs: ['./assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-gold-1.jpg',
        './assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-gold-2.jpg',
        './assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-gold-3.jpg',
        './assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-gold-4.jpg',
        './assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-gold-5.jpg',
        './assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-gold-6.jpg'],
        rating: 5,
        stock: 219,
        displaySize: `6.7''`,
        display: 'Super Retina XDR OLED',
        resolution: '2778 x 1284',
        ppi: '458ppi',
        refreshRate: '120Hz',
        communication: 'GPS; Wi-Fi; Bluetooth; Lightning',
        features: 'wireless charging; face ID; quick charge; LiDAR, emergency SOS via satellite',
        batteryType: 'Li-Ion',
        sdCardSupport: 'no',
        internet: '3G; 5G; 4G (LTE)',
        numOfSIMs: '1 + eSIM',
        typeOfSIM: 'Nano-SIM; eSIM',
        chipset: 'Apple A16 Bionic',
        cameras: '48MP + 12MP + 12MP + 12MP',
        maxVideoRecording: '2160p@60fps',
        bluetooth: '5.3',
        nfc: 'yes',
        os: 'iOS',
        osVersion: '16',
        protection: 'IP68',
        material: 'glass',
        size: '160.7 x 77.6 x 7.85mm',
        weight: '255g'
    },
    {
        id: '3',
        name: 'iPhone 14 Pro',
        category: 'smartphones',
        brand: 'apple',
        release: '2022',
        color: 'Silver',
        model: '(MQ1W3)',
        price: '1,299', 
        storage: '512Gb',
        imgs: ['./assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-silver-1.jpg',
        './assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-silver-2.jpg',
        './assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-silver-3.jpg',
        './assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-silver-4.jpg',
        './assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-silver-5.jpg',
        './assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-silver-6.jpg'],
        rating: 5,
        stock: 56,
        displaySize: `6.1''`,
        display: 'Super Retina XDR OLED',
        resolution: '2532 x 1170',
        ppi: '460ppi',
        refreshRate: '120Hz',
        communication: 'GPS; Wi-Fi; Bluetooth; Lightning',
        features: 'wireless charging; face ID; quick charge; LiDAR, emergency SOS via satellite',
        batteryType: 'Li-Ion',
        sdCardSupport: 'no',
        internet: '3G; 5G; 4G (LTE)',
        numOfSIMs: '1 + eSIM',
        typeOfSIM: 'Nano-SIM; eSIM',
        chipset: 'Apple A16 Bionic',
        cameras: '48MP + 12MP + 12MP + 12MP',
        maxVideoRecording: '2160p@60fps',
        bluetooth: '5.3',
        nfc: 'yes',
        os: 'iOS',
        osVersion: '16',
        protection: 'IP68',
        material: 'glass',
        size: '147.5 x 71.5 x 7.85mm',
        weight: '215g'
    },
    {
        id: '4',
        name: 'iPhone 14 Pro',
        category: 'smartphones',
        brand: 'apple',
        release: '2022',
        color: 'Space Black',
        model: '(MPXV3)',
        price: '999', 
        storage: '128Gb',
        imgs: ['./assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-space-black-1.jpg',
        './assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-space-black-2.jpg',
        './assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-space-black-3.jpg',
        './assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-space-black-4.jpg',
        './assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-space-black-5.jpg',
        './assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-space-black-6.jpg'],
        rating: 5,
        stock: 182,
        displaySize: `6.1''`,
        display: 'Super Retina XDR OLED',
        resolution: '2532 x 1170',
        ppi: '460ppi',
        refreshRate: '120Hz',
        communication: 'GPS; Wi-Fi; Bluetooth; Lightning',
        features: 'wireless charging; face ID; quick charge; LiDAR, emergency SOS via satellite',
        batteryType: 'Li-Ion',
        sdCardSupport: 'no',
        internet: '3G; 5G; 4G (LTE)',
        numOfSIMs: '1 + eSIM',
        typeOfSIM: 'Nano-SIM; eSIM',
        chipset: 'Apple A16 Bionic',
        cameras: '48MP + 12MP + 12MP + 12MP',
        maxVideoRecording: '2160p@60fps',
        bluetooth: '5.3',
        nfc: 'yes',
        os: 'iOS',
        osVersion: '16',
        protection: 'IP68',
        material: 'glass',
        size: '147.5 x 71.5 x 7.85mm',
        weight: '215g'
    },
    {
        id: '5',
        name: 'AirPods 2nd Generation',
        category: 'headphones',
        brand: 'apple',
        release: '2019',
        color: 'White',
        model: '(MV7N2RU/A)',
        price: '129', 
        imgs: ['./assets/images/headphones/apple/airpods-2-nd-gen/airpods-2-nd-gen-1.jpg',
        './assets/images/headphones/apple/airpods-2-nd-gen/airpods-2-nd-gen-2.jpg',
        './assets/images/headphones/apple/airpods-2-nd-gen/airpods-2-nd-gen-3.jpg',
        './assets/images/headphones/apple/airpods-2-nd-gen/airpods-2-nd-gen-4.jpg',
        './assets/images/headphones/apple/airpods-2-nd-gen/airpods-2-nd-gen-5.jpg',
        './assets/images/headphones/apple/airpods-2-nd-gen/airpods-2-nd-gen-6.jpg'],
        rating: 5,
        stock: 36,
        bluetooth: '5.0',
        chipset: 'Apple H1',
        protection: 'No',
        earpieceDesign: 'In-ear',
        construction: 'TWS',
        connection: 'wireless',
        activeNoiseCancellation: 'No',
        numOfMics: '2',
        audioCodec: 'AAC',
        weight: '8g',
        caseWeight: '40g'
    },
    {
        id: '6',
        name: 'AirPods 3rd Generation',
        category: 'headphones',
        brand: 'apple',
        release: '2021',
        color: 'White',
        model: '(MME73TY/A)',
        price: '169', 
        imgs: ['./assets/images/headphones/apple/airpods-3rd-generation/airpods-3rd-generation-1.jpg',
        './assets/images/headphones/apple/airpods-3rd-generation/airpods-3rd-generation-2.jpg',
        './assets/images/headphones/apple/airpods-3rd-generation/airpods-3rd-generation-3.jpg',
        './assets/images/headphones/apple/airpods-3rd-generation/airpods-3rd-generation-4.jpg',
        './assets/images/headphones/apple/airpods-3rd-generation/airpods-3rd-generation-5.jpg',
        './assets/images/headphones/apple/airpods-3rd-generation/airpods-3rd-generation-6.jpg'],
        rating: 5,
        stock: 67,
        bluetooth: '5.0',
        chipset: 'Apple H1',
        protection: 'IPX4',
        earpieceDesign: 'In-ear',
        construction: 'TWS',
        connection: 'wireless',
        activeNoiseCancellation: 'No',
        numOfMics: '2',
        audioCodec: 'AAC',
        weight: '4.28g',
        caseWeight: '37.9'
    },
    {
        id: '7',
        name: `MacBook Pro M1 Pro 16'`,
        category: 'laptops',
        brand: 'apple',
        release: '2021',
        color: 'Space Gray',
        model: '(MK183UA/A)',
        price: '2,499', 
        storage: '512Gb',
        imgs: ['./assets/images/laptops/apple/macbook-pro-m1-pro-16/macbook-pro-m1-pro-16-space-grey-1.jpg',
        './assets/images/laptops/apple/macbook-pro-m1-pro-16/macbook-pro-m1-pro-16-space-grey-2.jpg',
        './assets/images/laptops/apple/macbook-pro-m1-pro-16/macbook-pro-m1-pro-16-space-grey-3.jpg',
        './assets/images/laptops/apple/macbook-pro-m1-pro-16/macbook-pro-m1-pro-16-space-grey-4.jpg',
        './assets/images/laptops/apple/macbook-pro-m1-pro-16/macbook-pro-m1-pro-16-space-grey-5.jpg',
        './assets/images/laptops/apple/macbook-pro-m1-pro-16/macbook-pro-m1-pro-16-space-grey-6.jpg'],
        rating: 5,
        stock: 231,
        displaySize: `16''`,
        display: 'Mini LED',
        coating: 'glossy',
        resolution: '3456 x 2234',
        ppi: '254ppi',
        refreshRate: '120Hz',
        communication: 'Wi-Fi; Bluetooth',
        features: 'fingerprint sensor, keyboard backlight',
        chipsetCores: '10',
        ram: '16Gb',
        storageType: 'SSD',
        storageSize: '512Gb',
        graphicsCardType: 'Integrated',
        chipset: ' Apple M1 Pro',
        os: 'MacOS',
        wifiStandart: 'IEEE 802.11 ax',
        ports: 'HDMI; Thunderbolt; SD card reader; Audio jack (3.5 mm)',
        protection: 'No',
        material: 'metal',
        size: '355.7 x 248.1 x 16.8mm',
        webCamera: '1080p',
        weight: '2.1kg'
    },
    {
        id: '8',
        name: 'Watch Ultra GPS + Cellular 49mm Titanium Case/Green Alpine Loop L',
        category: 'watches',
        brand: 'apple',
        release: '2022',
        color: 'Green',
        model: '(MQFP3UL/A)',
        price: '312', 
        imgs: ['./assets/images/watches/apple/apple-watch-ultra-gps+cellular-49mm-titanium/apple-watch-ultra-gps+cellular-49mm-titanium-green-1.jpg',
        './assets/images/watches/apple/apple-watch-ultra-gps+cellular-49mm-titanium/apple-watch-ultra-gps+cellular-49mm-titanium-green-2.jpg',
        './assets/images/watches/apple/apple-watch-ultra-gps+cellular-49mm-titanium/apple-watch-ultra-gps+cellular-49mm-titanium-green-3.jpg',
        './assets/images/watches/apple/apple-watch-ultra-gps+cellular-49mm-titanium/apple-watch-ultra-gps+cellular-49mm-titanium-green-4.jpg'],
        rating: 5,
        stock: 27,
        os: 'WatchOS',
        osVersion: '9.0',
        training: 'cycling, running, swimming',
        bodyShape: 'rectangle',
        control: 'buttons, touch screen',
        sensors: 'accelerometer, gyro, heart rate, barometer, always-on altimeter, compass, SpO2',
        communication: 'GPS; Wi-Fi; Bluetooth',
        nfc: 'yes',
        protection: 'IP6X',
        resolution: '410 x 502',
        display: 'Retina LTPO OLED',
        bluetooth: '5.3',
        storage: '32Gb',
        chipset: 'Apple S8',
        batteryType: 'Li-Ion',
        material: 'titan',
        size: '49 x 44 x 14.4mm',
        weight: '61.3g'
    },
    {
        id: '9',
        name: '12.9" iPad Pro Wi-Fi + Cellular',
        category: 'tabltes',
        brand: 'apple',
        release: '2022',
        color: 'Space Gray',
        model: '(MP1X3RK/A)',
        price: '1,799', 
        storage: '1Tb',
        imgs: ['./assets/images/tablets/apple/12.9-ipad-pro-wi-fi+cellular/12.9-ipad-pro-wi-fi+cellular-1.jpg',
        './assets/images/tablets/apple/12.9-ipad-pro-wi-fi+cellular/12.9-ipad-pro-wi-fi+cellular-2.jpg',
        './assets/images/tablets/apple/12.9-ipad-pro-wi-fi+cellular/12.9-ipad-pro-wi-fi+cellular-3.jpg',
        './assets/images/tablets/apple/12.9-ipad-pro-wi-fi+cellular/12.9-ipad-pro-wi-fi+cellular-4.jpg',
        './assets/images/tablets/apple/12.9-ipad-pro-wi-fi+cellular/12.9-ipad-pro-wi-fi+cellular-5.jpg',
        './assets/images/tablets/apple/12.9-ipad-pro-wi-fi+cellular/12.9-ipad-pro-wi-fi+cellular-6.jpg'],
        rating: 5,
        stock: 143,
        displaySize: `12.9''`,
        display: 'Liquid Retina XDR display',
        resolution: '2732 x 2048',
        ppi: '264ppi',
        refreshRate: '120Hz',
        chipsetTurboFrequency: '3.5Ghz',
        chipsetCores: '8',
        ram: '8Gb',
        communication: 'GPS; Wi-Fi; Bluetooth',
        features: 'dual camera; face ID; ',
        ports: 'USB Type-C',
        sdCardSupport: 'no',
        internet: '2G 3G; 5G; 4G (LTE)',
        numOfSIMs: '1 + eSIM',
        typeOfSIM: 'Nano-SIM; eSIM',
        chipset: 'Apple M2',
        cameras: '12MP + 10MP + 12MP',
        maxVideoRecording: '2160p@60fps',
        bluetooth: '5.3',
        os: 'iPadOS',
        osVersion: '16',
        protection: 'no',
        material: 'aluminum',
        size: '280.6 x 214.9 x 6.4mm',
        weight: '685g'
    },
    
    
]

export default productDB;