
import ProductInterface from '../models/products';

const productDB: ProductInterface[] = [
    {
        id: '1',
        name: 'Apple Iphone 14 Pro Max',
        category: 'smartphone',
        brand: 'Apple',
        release: '5 September',
        rating: 5,
        color: 'Black',
        model: '(MQ2N3)',
        price: '456',
        capacity: '1TB',    
        img: './assets/images/image_test_1.png',
        availabilityCount: 457 
    },
    {
        id: '2',
        name: 'Apple Iphone 14',
        category: 'smartphone',
        brand: 'Apple',
        release: '5 September',
        rating: 5,
        color: 'Gold',
        model: '(MPVN3)',
        price: '456',
        capacity: '512GB',    
        img: './assets/images/image_test_2.png',
        availabilityCount: 245 
    },
    {
        id: '3',
        name: 'Apple Iphone 13',
        category: 'smartphone',
        brand: 'Apple',
        release: '5 September',
        rating: 5,
        color: 'Dark',
        model: '(MNGL3)',
        price: '456',
        capacity: '512GB',    
        img: './assets/images/image_test_3.png',
        availabilityCount: 134 
    },
    {
        id: '4',
        name: 'Apple Iphone 14 Pro Max',
        category: 'smartphone',
        brand: 'Apple',
        release: '5 September',
        rating: 5,
        color: 'Black',
        model: '(MQ2N3)',
        price: '456',
        capacity: '512GB',    
        img: './assets/images/image_test_1.png',
        availabilityCount: 457 
    },
    {
        id: '5',
        name: 'Apple Iphone 14',
        category: 'smartphone',
        brand: 'Apple',
        release: '5 September',
        rating: 5,
        color: 'Gold',
        model: '(MPVN3)',
        price: '456',
        capacity: '512GB',    
        img: './assets/images/image_test_2.png',
        availabilityCount: 245 
    },
    {
        id: '6',
        name: 'Apple Iphone 13',
        category: 'smartphone',
        brand: 'Apple',
        release: '5 September',
        rating: 5,
        color: 'Dark',
        model: '(MNGL3)',
        price: '456',
        capacity: '512GB',    
        img: './assets/images/image_test_3.png',
        availabilityCount: 134 
    },    
    {
        id: '7',
        name: 'Apple Iphone',
        category: 'smartphone',
        brand: 'Apple',
        release: '5 September',
        rating: 5,
        color: 'dark',
        model: '14 Pro',
        price: '456',
        capacity: '256GB',    
        img: './assets/images/Apple iPhone 14 Pro Max black back.jpeg',
        availabilityCount: 273 
    },
    {
        id: '8',
        name: 'Apple Iphone',
        category: 'smartphone',
        brand: 'Apple',
        release: '5 September',
        rating: 5,
        color: 'white',
        model: '14 Pro',
        price: '456',
        capacity: '256 GB',    
        img: './assets/images/Apple iPhone 14 Pro Max black back.jpeg',
        availabilityCount: 925 
    },
    {
        id: '9',
        name: 'Apple Iphone',
        category: 'smartphone',
        brand: 'Apple',
        release: '5 September',
        rating: 5,
        color: 'black',
        model: '14',
        price: '456',
        capacity: '128 GB',    
        img: './assets/images/Apple iPhone 14 Pro Max black back.jpeg',
        availabilityCount: 422 
    },
    {
        id: '10',
        name: 'Apple Iphone',
        category: 'smartphone',
        brand: 'Apple',
        release: '5 September',
        rating: 5,
        color: 'gold',
        model: '14',
        price: '456',
        capacity: '128 GB',    
        img: './assets/images/Apple iPhone 14 Pro Max black back.jpeg',
        availabilityCount: 724 
    },
    {
        id: '11',
        name: 'Apple Iphone',
        category: 'smartphone',
        brand: 'Apple',
        release: '5 September',
        rating: 5,
        color: 'dark',
        model: '14',
        price: '456',
        capacity: '128 GB',    
        img: './assets/images/Apple iPhone 14 Pro Max black back.jpeg',
        availabilityCount: 134 
    },
    {
        id: '12',
        name: 'Apple Iphone',
        category: 'smartphone',
        brand: 'Apple',
        release: '5 September',
        rating: 5,
        color: 'white',
        model: '14',
        price: '456',
        capacity: '128 GB',    
        img: './assets/images/Apple iPhone 14 Pro Max black back.jpeg',
        availabilityCount: 5 
    },
    {
        id: '13',
        name: 'Apple MacBook',
        category: 'laptop',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'black',
        model: 'Air 13 M2 16C',
        price: '456',
        capacity: '512 GB',    
        img: './assets/images/Apple MacBook Air 13 M2 16C CPU8C GPU 2022 8 GB 512 GB SSD bottom.jpg',
        availabilityCount: 129 
    },
    {
        id: '14',
        name: 'Apple MacBook',
        category: 'laptop',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'white',
        model: 'Air 13 M2 16C',
        price: '456',
        capacity: '512 GB',    
        img: './assets/images/Apple MacBook Air 13 M2 16C CPU8C GPU 2022 8 GB 512 GB SSD bottom.jpg',
        availabilityCount: 542 
    },
    {
        id: '15',
        name: 'Apple MacBook',
        category: 'laptop',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'dark',
        model: 'Air 13 M2 16C',
        price: '456',
        capacity: '512 GB',    
        img: './assets/images/Apple MacBook Air 13 M2 16C CPU8C GPU 2022 8 GB 512 GB SSD bottom.jpg',
        availabilityCount: 231 
    },
    {
        id: '16',
        name: 'Apple MacBook',
        category: 'laptop',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'gray',
        model: 'Air 13 M2 16C',
        price: '456',
        capacity: '512 GB',    
        img: './assets/images/Apple MacBook Air 13 M2 16C CPU8C GPU 2022 8 GB 512 GB SSD bottom.jpg',
        availabilityCount: 245 
    },
    {
        id: '17',
        name: 'Apple MacBook',
        category: 'laptop',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'black',
        model: 'Air 13 M2 10C',
        price: '456',
        capacity: '256 GB',    
        img: './assets/images/Apple MacBook Air 13 M2 16C CPU8C GPU 2022 8 GB 512 GB SSD bottom.jpg',
        availabilityCount: 323 
    },
    {
        id: '18',
        name: 'Apple MacBook',
        category: 'laptop',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'white',
        model: 'Air 13 M2 10C',
        price: '456',
        capacity: '256 GB',    
        img: './assets/images/Apple MacBook Air 13 M2 16C CPU8C GPU 2022 8 GB 512 GB SSD bottom.jpg',
        availabilityCount: 873 
    },
    {
        id: '19',
        name: 'Apple MacBook',
        category: 'laptop',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'dark',
        model: 'Air 13 M2 10C',
        price: '456',
        capacity: '256 GB',    
        img: './assets/images/Apple MacBook Air 13 M2 16C CPU8C GPU 2022 8 GB 512 GB SSD bottom.jpg',
        availabilityCount: 736 
    },
    {
        id: '20',
        name: 'Apple MacBook',
        category: 'laptop',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'gray',
        model: 'Air 13 M2 10C',
        price: '456',
        capacity: '256 GB',    
        img: './assets/images/Apple MacBook Air 13 M2 16C CPU8C GPU 2022 8 GB 512 GB SSD bottom.jpg',
        availabilityCount: 121 
    },
    {
        id: '21',
        name: 'Apple MacBook',
        category: 'laptop',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'black',
        model: 'Air 13 M2 8C',
        price: '456',
        capacity: '128 GB',    
        img: './assets/images/Apple MacBook Air 13 M2 16C CPU8C GPU 2022 8 GB 512 GB SSD bottom.jpg',
        availabilityCount: 555 
    },
    {
        id: '22',
        name: 'Apple MacBook',
        category: 'laptop',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'white',
        model: 'Air 13 M2 8C',
        price: '456',
        capacity: '128 GB',    
        img: './assets/images/Apple MacBook Air 13 M2 16C CPU8C GPU 2022 8 GB 512 GB SSD bottom.jpg',
        availabilityCount: 1541 
    },
    {
        id: '23',
        name: 'Apple MacBook',
        category: 'laptop',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'dark',
        model: 'Air 13 M2 8C',
        price: '456',
        capacity: '128 GB',    
        img: './assets/images/Apple MacBook Air 13 M2 16C CPU8C GPU 2022 8 GB 512 GB SSD bottom.jpg',
        availabilityCount: 890 
    },
    {
        id: '24',
        name: 'Apple MacBook',
        category: 'laptop',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'gray',
        model: 'Air 13 M2 8C',
        price: '456',
        capacity: '128 GB',    
        img: './assets/images/Apple MacBook Air 13 M2 16C CPU8C GPU 2022 8 GB 512 GB SSD bottom.jpg',
        availabilityCount: 125 
    },
    {
        id: '25',
        name: 'Apple IPad',
        category: 'tablet',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'black',
        model: 'Pro',
        price: '456',
        capacity: '512 GB',    
        img: './assets/images/Apple iPad Pro 2021 13 Wi-Fi 256 space front.jpg',
        availabilityCount: 97 
    },
    {
        id: '26',
        name: 'Apple IPad',
        category: 'tablet',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'silver',
        model: 'Pro',
        price: '456',
        capacity: '512 GB',    
        img: './assets/images/Apple iPad Pro 2021 13 Wi-Fi 256 space front.jpg',
        availabilityCount: 515 
    },
    {
        id: '27',
        name: 'Apple IPad',
        category: 'tablet',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'space',
        model: 'Pro',
        price: '456',
        capacity: '512 GB',    
        img: './assets/images/Apple iPad Pro 2021 13 Wi-Fi 256 space front.jpg',
        availabilityCount: 232 
    },
    {
        id: '28',
        name: 'Apple IPad',
        category: 'tablet',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'space',
        model: '10',
        price: '456',
        capacity: '256 GB',    
        img: './assets/images/Apple iPad Pro 2021 13 Wi-Fi 256 space front.jpg',
        availabilityCount: 157 
    },
    {
        id: '29',
        name: 'Apple IPad',
        category: 'tablet',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'silver',
        model: '10',
        price: '456',
        capacity: '256 GB',    
        img: './assets/images/Apple iPad Pro 2021 13 Wi-Fi 256 space front.jpg',
        availabilityCount: 4455 
    },
    {
        id: '30',
        name: 'Apple IPad',
        category: 'tablet',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'black',
        model: '10',
        price: '456',
        capacity: '256 GB',    
        img: './assets/images/Apple iPad Pro 2021 13 Wi-Fi 256 space front.jpg',
        availabilityCount: 16516 
    },
    {
        id: '31',
        name: 'Apple IPad',
        category: 'tablet',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'gray',
        model: 'mini',
        price: '456',
        capacity: '64 GB',    
        img: './assets/images/Apple iPad Pro 2021 13 Wi-Fi 256 space front.jpg',
        availabilityCount: 5235 
    },
    {
        id: '32',
        name: 'Apple IPad',
        category: 'tablet',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'pink',
        model: 'mini',
        price: '456',
        capacity: '64 GB',    
        img: './assets/images/Apple iPad Pro 2021 13 Wi-Fi 256 space front.jpg',
        availabilityCount: 7271 
    },
    {
        id: '33',
        name: 'Apple Watch',
        category: 'watch',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'beige',
        model: 'Ultra',
        price: '999',
        capacity: '32 GB',    
        img: './assets/images/Apple Watch Ultra GPS + Cellular 49 beige front.jpg',
        availabilityCount: 2356 
    },
    {
        id: '34',
        name: 'Apple Watch',
        category: 'watch',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'black',
        model: 'Ultra',
        price: '999',
        capacity: '32 GB',    
        img: './assets/images/Apple Watch Ultra GPS + Cellular 49 beige front.jpg',
        availabilityCount: 322 
    },
    {
        id: '35',
        name: 'Apple Watch',
        category: 'watch',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'blue',
        model: 'Ultra',
        price: '999',
        capacity: '32 GB',    
        img: './assets/images/Apple Watch Ultra GPS + Cellular 49 beige front.jpg',
        availabilityCount: 322 
    },
    {
        id: '36',
        name: 'Apple Watch',
        category: 'watch',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'blue',
        model: 'Series 7',
        price: '999',
        capacity: '16 GB',    
        img: './assets/images/Apple Watch Ultra GPS + Cellular 49 beige front.jpg',
        availabilityCount: 322 
    },
    {
        id: '37',
        name: 'Apple Watch',
        category: 'watch',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'gray',
        model: 'Series 7',
        price: '999',
        capacity: '16 GB',    
        img: './assets/images/Apple Watch Ultra GPS + Cellular 49 beige front.jpg',
        availabilityCount: 322 
    },
    {
        id: '38',
        name: 'Apple Watch',
        category: 'watch',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'white',
        model: 'Series 7',
        price: '999',
        capacity: '16 GB',    
        img: './assets/images/Apple Watch Ultra GPS + Cellular 49 beige front.jpg',
        availabilityCount: 322 
    },
    {
        id: '39',
        name: 'Apple Watch',
        category: 'watch',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'white',
        model: 'SE',
        price: '999',
        capacity: '8 GB',    
        img: './assets/images/Apple Watch Ultra GPS + Cellular 49 beige front.jpg',
        availabilityCount: 322 
    },
    {
        id: '40',
        name: 'Apple Watch',
        category: 'watch',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'pink',
        model: 'SE',
        price: '999',
        capacity: '8 GB',    
        img: './assets/images/Apple Watch Ultra GPS + Cellular 49 beige front.jpg',
        availabilityCount: 322 
    },
    {
        id: '41',
        name: 'Apple Watch',
        category: 'watch',
        brand: 'Apple',
        release: '15 September',
        rating: 5,
        color: 'yellow',
        model: 'SE',
        price: '999',
        capacity: '8 GB',    
        img: './assets/images/Apple Watch Ultra GPS + Cellular 49 beige front.jpg',
        availabilityCount: 322 
    },
    
]

export default productDB;