
import ProductInterface from '../models/products';

const productDB: ProductInterface[] = [
    {
        id: '1',
        name: 'iPhone 14 Pro Max',
        category: 'smarthones',
        brand: 'apple',
        release: '2022',
        color: 'Deep Purple',
        model: '(MQC53)',
        price: '1599', 
        memory: '1Tb',
        imgs: ['./assets/images/smartphones/iphones/iphone-14-pro-max/deep-purple/iphone-14-pro-max-deep-purple-1.jpg',
        './assets/images/smartphones/iphones/iphone-14-pro-max/deep-purple/iphone-14-pro-max-deep-purple-2.jpg',
        './assets/images/smartphones/iphones/iphone-14-pro-max/deep-purple/iphone-14-pro-max-deep-purple-3.jpg',
        './assets/images/smartphones/iphones/iphone-14-pro-max/deep-purple/iphone-14-pro-max-deep-purple-4.jpg',
        './assets/images/smartphones/iphones/iphone-14-pro-max/deep-purple/iphone-14-pro-max-deep-purple-5.jpg',
        './assets/images/smartphones/iphones/iphone-14-pro-max/deep-purple/iphone-14-pro-max-deep-purple-6.jpg'],
        rating: 5,
        stock: 101,
        displaySize: `6.7''`,
        display: 'Super Retina XDR OLED',
        resolution: '2778x1284',
        ppi: '458ppi',
        refreshRate: '120Hz',
        communication: 'GPS; Wi-Fi; Bluetooth; Lightning; NFC',
        features: 'wireless charging; face ID; quick charge; LiDAR, emergency SOS via satellite',
        batteryType: 'Li-Ion',
        sdCardSupport: 'no support',
        internet: '3G; 5G; 4G (LTE)',
        numOfSIMs: '1 + eSIM',
        typeOfSIM: 'Nano-SIM; eSIM',
        chipset: 'Apple A16 Bionic',
        cameras: '48MP + 12MP + 12MP + 12MP',
        maxVideoRecording: '2160p@60fps',
        bluetooth: '5.3',
        nfc: 'yes',
        os: 'iOS',
        osVersion: '16',
        protection: 'IP68',
        material: 'glass',
        size: '160.7 x 77.6 x 7.85mm',
        weight: '255g'
    },
    {
        id: '2',
        name: 'iPhone 14 Pro Max',
        category: 'smarthones',
        brand: 'apple',
        release: '2022',
        color: 'Gold',
        model: '(MQC53)',
        price: '1199', 
        memory: '256Tb',
        imgs: ['./assets/images/smartphones/iphones/iphone-14-pro-max/gold/iphone-14-pro-max-gold-1.jpg',
        './assets/images/smartphones/iphones/iphone-14-pro-max/gold/iphone-14-pro-max-gold-2.jpg',
        './assets/images/smartphones/iphones/iphone-14-pro-max/gold/iphone-14-pro-max-gold-3.jpg',
        './assets/images/smartphones/iphones/iphone-14-pro-max/gold/iphone-14-pro-max-gold-4.jpg',
        './assets/images/smartphones/iphones/iphone-14-pro-max/gold/iphone-14-pro-max-gold-5.jpg',
        './assets/images/smartphones/iphones/iphone-14-pro-max/gold/iphone-14-pro-max-gold-6.jpg'],
        rating: 2,
        stock: 219,
        displaySize: `6.7''`,
        display: 'Super Retina XDR OLED',
        resolution: '2778x1284',
        ppi: '458ppi',
        refreshRate: '120Hz',
        communication: 'GPS; Wi-Fi; Bluetooth; Lightning; NFC',
        features: 'wireless charging; face ID; quick charge; LiDAR, emergency SOS via satellite',
        batteryType: 'Li-Ion',
        sdCardSupport: 'no support',
        internet: '3G; 5G; 4G (LTE)',
        numOfSIMs: '1 + eSIM',
        typeOfSIM: 'Nano-SIM; eSIM',
        chipset: 'Apple A16 Bionic',
        cameras: '48MP + 12MP + 12MP + 12MP',
        maxVideoRecording: '2160p@60fps',
        bluetooth: '5.3',
        nfc: 'yes',
        os: 'iOS',
        osVersion: '16',
        protection: 'IP68',
        material: 'glass',
        size: '160.7 x 77.6 x 7.85mm',
        weight: '255g'
    }
    
    
]

export default productDB;